site_name: ATM Documentation
site_url: https://thieleju.github.io/ATM/
site_description: Project documentation with Markdown.
site_author: Die Panzerknacker

repo_url: https://github.com/thieleju/atm/
edit_uri: ""

nav:
  - Home: index.md
  - About: about.md

