@startuml usecase

left to right direction
skinparam packageStyle rectangle

actor "Benutzer" as AB
actor "Administrator" as AA

AB <- AA

rectangle ATM {

  AB -- (Login)
  AB -- (Logout)

  (Login) <.- (Kontostand anzeigen) : "<<extend>>"
  (Login) <.- (Geld abheben) : "<<extend>>"
  (Login) <.- (Geld einzahlen) : "<<extend>>"

  AA -- (Login)
  AA -- (Logout)
  AA -- (Admin-Ansicht)

  (Admin-Ansicht) <.- (Account hinzufügen) : "<<extend>>"
  (Admin-Ansicht) <.- (Account löschen) : "<<extend>>"
  (Admin-Ansicht) <.- (Accountguthaben bearbeiten) : "<<extend>>"
}

@enduml
