site_name: ATM Dokumenation
site_url: https://thieleju.github.io/ATM/
site_description: ATM Projektdokumentation
site_author: Die Panzerknacker

repo_url: github.com/thieleju/atm
edit_uri: ""

theme: jekyll-theme-slate

nav:
    - Home: index.md
    - About: about.md
