name: Publish MkDocs via GitHub Pages
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: |
          pip install --upgrade pip 
          pip install mkdocs
          pip install mkdocs-gen-files
          pip install mkdocs-material
          pip install mkdocs-with-pdf

      - name: Setup Git Config
        run: |
          git config user.name 'github-actions[bot]' 
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Deploy docs to gh-pages branch
        run: mkdocs gh-deploy --config-file docs/mkdocs.yml

      - run: ls

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MkDocsPDF
          path: docs.pdf
